In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [5]:
a[:3]

array([10,  2,  3])

In [6]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
print(a[1, 3])


8


In [9]:
a.ndim

2

In [10]:
print(a.shape)
print(len(a.shape) == a.ndim)

(3, 4)
True


In [11]:
a.size

12

In [12]:
import math
a.size == math.prod(a.shape)

True

In [13]:
a.dtype

dtype('int64')

In [14]:
np.zeros(2)

array([0., 0.])

In [15]:
np.ones(2)

array([1., 1.])

In [16]:
np.empty(2)

array([1., 1.])

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [19]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [21]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
print(np.sort(arr))


[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [24]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

In [29]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [30]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [31]:
np.reshape(a, (1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [33]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [34]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [35]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [37]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [38]:
c = np.expand_dims(a, axis=0)
c.shape
(1, 6)

(1, 6)

In [39]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [41]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [42]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [43]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [44]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [45]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [46]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [47]:
print(a[b])

[1 2 3 4]


In [48]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [49]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [50]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [51]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [52]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [53]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [54]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [56]:
b1 = a[0, :]
print(b1)
b1[0] = 99
print(b1)
print(a)

[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
b2 = a.copy()

In [58]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [59]:
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


In [60]:
a = np.array([1, 2, 3, 4])
print(a.sum())

10


In [61]:
b = np.array([[1, 1], [2, 2]])
print(b.sum(axis=0))

[3 3]


In [62]:
b.sum(axis=1)

array([2, 4])

In [63]:
data = np.array([1.0, 2.0])
print(data * 1.6)

[1.6 3.2]


In [64]:
data = np.array([1, 2, 3])
print(data.max())
print(data.min())
print(data.sum())

3
1
6


In [66]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(a.sum())
print(a.min())
print(a.min(axis=0))


4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]


In [67]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [69]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])
print(data.max())
print(data.min())
print(data.sum())

2
[[3 4]
 [5 6]]
[1 3]
6
1
21


In [70]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


In [71]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print(data + ones)


[[2 3]
 [4 5]]


In [72]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print(data + ones_row)

[[2 3]
 [4 5]
 [6 7]]


In [73]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [74]:
print(np.ones(3))
print(np.zeros(3))
rng = np.random.default_rng()
print(rng.random(3))
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(rng.random((3, 2)) )

[1. 1. 1.]
[0. 0. 0.]
[0.03732147 0.54611227 0.69329215]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.89707213 0.1144509 ]
 [0.27267266 0.81711464]
 [0.01481184 0.29462484]]


In [75]:
rng.integers(5, size=(2, 4))

array([[3, 0, 2, 1],
       [3, 3, 3, 4]])

In [77]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [78]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [79]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)


[3 2 2 2 1 1 1 1 1 1]


In [80]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [81]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [83]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [84]:
print(data.reshape(2, 3))
print(data.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [85]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [86]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [87]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [89]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [90]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [91]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [92]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]
